networks:
  traefik:
    external: true

services:
  frontend:
    image: nginx:latest
    restart: unless-stopped
    working_dir: /var/www/html
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.biozuglo.rule=${FRONTEND_HOST}
      - traefik.http.routers.biozuglo.entrypoints=websecure
      - traefik.http.routers.biozuglo.tls=true
      - traefik.http.routers.biozuglo.tls.certresolver=myresolver
      - traefik.log.level=${LOG_LEVEL}
      - traefik.http.services.biozuglo.loadbalancer.server.port=80
    volumes:
      - ./dist/browser:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik
